database:
  host: localhost
  name: spicyazisaban
  user: spicyazisaban
  password: naetao
  verifyServerCertificate: false
  useSSL: true
  # Send keep alive every n seconds
  keepAlive: 300
  # If true, the plugin will prevent players from joining the server if database is inaccessible.
  failsafe: true
serverNames:
  # "server" (key) must not contain UPPERCASE character.
  server: FriendlyServerName
defaultReasons:
  # valid types: ban, temp_ban, ip_ban, temp_ip_ban, mute, temp_mute, ip_mute, temp_ip_mute, warning, caution, kick, note
  # invalid types are ignored
  ban:
    # <server/group/global>: reasons list
    global:
      - "ban reason (global) 1"
      - "ban reason (global) 2"
    lobby:
      - "ban reason (lobby) 1"
      - "ban reason (lobby) 2"
blockedCommandsWhenMuted:
  - tell
  - r
  - me
banOnWarning:
  # if warning count hits 3, the player would be banned with specified reason
  # this feature will be disabled if you set this value to <= 0
  threshold: 3
  time: "1mo"
  reason: ":boom:"
